### PR TITLE
fix(hotfix16): drop missing JWTAuth fields + adapt ClickHouse aggregate handlers

### LINKED ISSUE #12539: Build broken on 2026.02.02.0-hotfix16 — JWTAuth missing fields & Platform missing AuthInfo helpers
## Summary

`cargo build --release --features release --features v1` fails on the `2026.02.02.0-hotfix16-hotfix` branch (and on tag `2026.02.02.0-hotfix16-11` that was just cut from it). The router crate references APIs that exist on `main` but were never backported to this hotfix line.

## Build error

\`\`\`
error[E0560]: struct \`JWTAuth\` has no field named \`allow_connected\`
   --> crates/router/src/routes/payment_methods.rs:632:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_platform\`
   --> crates/router/src/routes/payment_methods.rs:633:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_connected\`
   --> crates/router/src/analytics.rs:771:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_platform\`
   --> crates/router/src/analytics.rs:772:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_connected\`
   --> crates/router/src/analytics.rs:813:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_platform\`
   --> crates/router/src/analytics.rs:814:17
error[E0599]: no method named \`to_merchant_level_auth_info\` found for struct \`Platform\`
   --> crates/router/src/analytics.rs:759:47
error[E0599]: no method named \`to_profile_level_auth_info\` found for struct \`Platform\`
   --> crates/router/src/analytics.rs:801:47
error: could not compile \`router\` (lib) due to 8 previous errors
\`\`\`

## Root cause

Two PRs on `main` provided the missing APIs but were never backported to `2026.02.02.0-hotfix16-*`:

- [#11195](https://github.com/juspay/hyperswitch/pull/11195) `feat(platform): JWT Authentication for Platform Operations` — added `allow_connected: bool` / `allow_platform: bool` to `JWTAuth` (this branch's struct still only carries `permission`).
- [#11635](https://github.com/juspay/hyperswitch/pull/11635) `feat(platform): modify queries to support analytics for connected merchant` — added `Platform::to_merchant_level_auth_info()` / `to_profile_level_auth_info()`.

## Where the broken references came in

- [#12432](https://github.com/juspay/hyperswitch/pull/12432) (shipped in `-hotfix16-10`) — analytics aggregate handlers using both of the above main-only APIs.
- [#12523](https://github.com/juspay/hyperswitch/pull/12523) (shipped in `-hotfix16-11`) — cherry-pick of #11595 adding a JWT branch in `list_payment_method_api` that uses the missing `JWTAuth` fields.

Neither broke at merge because the only verification was on `main` (where the APIs exist).

## Impact

- `2026.02.02.0-hotfix16-11` Docker image cannot be built from source — `cargo build` aborts in `[builder 5/5]`.
- Any further hotfix on this line will be blocked until the build is unblocked.

## Fix

PR #12538 — surgical adapt without backporting the two feature PRs:

- `analytics.rs`: inline-construct `AuthInfo::MerchantLevel` / `AuthInfo::ProfileLevel` from `auth.platform.get_processor()` (matches the pattern already used by sibling handlers in the file), and drop `allow_connected` / `allow_platform` from the `JWTAuth` literals.
- `payment_methods.rs`: drop `allow_connected` / `allow_platform` from the `JWTAuth` literal in `list_payment_method_api`.

Standard / Platform merchant behavior unchanged. Connected-merchant gating that #11195 + #11635 provide on `main` is **not** available on this hotfix line and is intentionally not introduced.

## Action items

- [ ] Merge PR #12538
- [ ] Cut a new revision (`-hotfix16-12` or `-hotfix16-11.1`) and rebuild the Docker image
- [ ] Decide whether to formally backport #11195 + #11635 to this hotfix line for future-proofing, or leave Connected-merchant gating limited to `main`
- [ ] Add a CI guard so future hotfix-line PRs run `cargo check --release --features release --features v1` before merge

### PR DESCRIPTION
**Pull request by VenuMadhav2541**
## Summary

`2026.02.02.0-hotfix16-11` (tag just cut from PR #12523) does not compile. Two PRs that are on `main` were never backported to this hotfix line, and code on the branch references their APIs:

- [#11195](https://github.com/juspay/hyperswitch/pull/11195) `feat(platform): JWT Authentication for Platform Operations` — added `allow_connected: bool` / `allow_platform: bool` to `JWTAuth` (the branch-local struct still only carries `permission`).
- [#11635](https://github.com/juspay/hyperswitch/pull/11635) `feat(platform): modify queries to support analytics for connected merchant` — added `Platform::to_merchant_level_auth_info()` / `to_profile_level_auth_info()`.

## Build error before this fix

```
error[E0560]: struct \`JWTAuth\` has no field named \`allow_connected\`
   --> crates/router/src/routes/payment_methods.rs:632:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_platform\`
   --> crates/router/src/routes/payment_methods.rs:633:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_connected\`
   --> crates/router/src/analytics.rs:771:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_platform\`
   --> crates/router/src/analytics.rs:772:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_connected\`
   --> crates/router/src/analytics.rs:813:17
error[E0560]: struct \`JWTAuth\` has no field named \`allow_platform\`
   --> crates/router/src/analytics.rs:814:17
error[E0599]: no method named \`to_merchant_level_auth_info\` found for struct \`Platform\`
   --> crates/router/src/analytics.rs:759:47
error[E0599]: no method named \`to_profile_level_auth_info\` found for struct \`Platform\`
   --> crates/router/src/analytics.rs:801:47
error: could not compile \`router\` (lib) due to 8 previous errors
```

Source PRs that introduced the offending references on this branch:

- [#12432](https://github.com/juspay/hyperswitch/pull/12432) (shipped in `-hotfix16-10`) — added the two ClickHouse aggregate handlers in `analytics.rs` that call `Platform::to_*_level_auth_info()` and use the missing `JWTAuth` fields.
- [#12523](https://github.com/juspay/hyperswitch/pull/12523) (shipped in `-hotfix16-11`) — cherry-picked #11595, which adds the JWT branch in `list_payment_method_api` and uses the same missing `JWTAuth` fields.

## Approach

Surgical adapt, no upstream feature backport (a full port of #11195 + #11635 would be a feature-merge on a frozen tag line, not a hotfix).

**Commit 1 — `analytics.rs`:** Inline-construct `AuthInfo::MerchantLevel` and `AuthInfo::ProfileLevel` from `auth.platform.get_processor()` exactly like the sibling handlers already in the file ([analytics.rs:557](crates/router/src/analytics.rs#L557), [:669](crates/router/src/analytics.rs#L669)). Drop `allow_connected` / `allow_platform` from the two `JWTAuth` literals.

**Commit 2 — `payment_methods.rs`:** Drop `allow_connected` / `allow_platform` from the `JWTAuth` literal in `list_payment_method_api`. The JWT branch stays functional with the `permission` field that does exist on this branch's struct.

## Behavior

- **Standard / Platform merchants:** unchanged. Same response shape, same auth requirements.
- **Connected-merchant gating** introduced by #11195 + #11635 on main is **not available on this hotfix line** and is intentionally not introduced here. Coverage is consistent with the rest of `-hotfix16-*`.

## Test plan

- [ ] Docker build succeeds: `docker buildx build --build-arg BINARY=router --build-arg VERSION_FEATURE_SET=v1 --features release ...`
- [ ] `GET /payment_methods` works with JWT (no client_secret), with publishable-key + client_secret, and with API key
- [ ] `GET /analytics/v1/payment_intents/aggregate` returns `status_with_count` for a Standard merchant JWT
- [ ] `GET /analytics/v1/profile/payment_intents/aggregate` returns `status_with_count` for a profile-scoped JWT

Tracker: #12539

### CODE REVIEW

**Review by rohanm13 — APPROVED** [review]

**Review by XyneSpaces — APPROVED** [review]
## Review Summary

**PR Type:** Hotfix compilation fix for `2026.02.02.0-hotfix16-11`
**Scope:** Removes references to `JWTAuth` fields and `Platform` methods not present on this branch
**Risk Level:** Low

---

### Changes Analysis

Clean surgical fix addressing compilation errors introduced by backporting PRs that depend on unbackported features:

1. **analytics.rs (2 handlers)** - Replaces calls to `to_merchant_level_auth_info()` and `to_profile_level_auth_info()` with inline `AuthInfo` construction using the same pattern as sibling handlers (lines 557, 669). Correctly maintains existing authorization behavior.

2. **payment_methods.rs** - Removes `allow_connected` and `allow_platform` fields from `JWTAuth` literal in `list_payment_method_api`. The struct on this branch only has `permission` field.

### Baseline Checks

- ✅ No new `.unwrap()` / `.expect()` in production code
- ✅ No new `unsafe` blocks
- ✅ `error_stack` propagation preserved
- ✅ No sensitive data exposure
- ✅ Feature gate usage correct (`#[cfg(feature = "v1/v2")]` preserved)
- ✅ No new panics introduced

### Intent Acknowledged

The PR explicitly notes that connected-merchant gating (from main branch PRs #11195 and #11635) is intentionally **not** introduced on this hotfix line. This is appropriate for a frozen tag line - hotfixes should fix compilation, not introduce new features.

### Build Verification Required

Per test plan in PR description, Docker build must succeed before merge. The diff appears syntactically correct and matches the patterns from sibling handlers.

---

**Verdict:** `approve` - Clean hotfix that restores compilation without changing runtime behavior for standard/platform merchants.

**Review by XyneSpaces — COMMENTED** [review]
## Automated Review Summary

**PR Type:** Hotfix compilation fix  
**Scope:** Removing references to missing JWTAuth fields and Platform methods  
**Risk Level:** Low

### Analysis

This PR surgically adapts the hotfix branch to compile by:
1. Removing `allow_connected`/`allow_platform` fields from `JWTAuth` literals (lines 771-773, 819-821 in analytics.rs; lines 632-633 in payment_methods.rs)
2. Replacing `Platform::to_merchant_level_auth_info()` / `to_profile_level_auth_info()` calls with inline `AuthInfo` construction

### Verification

- ✅ Correct hotfix approach — no feature backport to frozen tag line
- ✅ `AuthInfo` construction matches sibling handlers in file (lines 557, 669)
- ✅ `permission` field preserved on existing `JWTAuth` struct
- ✅ No new unwrap/expect calls
- ✅ No sensitive data handling

### Notes

- The inline construction extracts `org_id` and `merchant_id` via `auth.platform.get_processor().get_account()` chain
- Connected-merchant gating from #11195/#11635 remains unavailable on this hotfix line (documented as intentional)

**Review by gitanjli525 — APPROVED** [review]
